export const SEARCH_QUERY = 'SEARCH_QUERY';
export const QUERY_RESOLVED = 'QUERY_RESOLVED';
export const QUERY_REJECTED = 'QUERY_REJECTED';
export const QUERY_LOADING = 'QUERY_LOADING';
export const RESET_OFFSET = 'RESET_OFFSET';
export const OFFSET_UP = 'OFFSET_UP';
export const OFFSET_DOWN = 'OFFSET_DOWN';
